name: CI

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: "Install node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit tests
        run: php build/bin/codecept run unit

      - name: Install maildev
        run: npm install -g maildev

      - name: Run maildev
        run: maildev -v --ip 0.0.0.0 --hide-extensions STARTTLS &

      - name: Run Acceptance tests
        run: php build/bin/codecept run acceptance
